PT_Online/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from anasayfa import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name="index"),
    url(r'^ilkay/', include("anasayfa.urls")),
    url(r'^kullanicilar/', include("kullanicilar.urls")),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

anasayfa/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "anasayfa"

urlpatterns = [
    path('cv/',views.ilkay,name = "ilkay"),
    path('hizmetler/',views.hizmetler,name = "hizmetler"),

]

kullanicilar/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views


app_name = "kullanicilar"

urlpatterns = [
    url(r'^kayit/',views.kayit,name = "kayit"),
    url(r'^giris/',views.giris,name = "giris"),
    url(r'^cikis/',views.cikis,name = "cikis"),
    url(r'^profil/',views.profil_goruntule,name = "profil_goruntule"),
    url(r'^sifre/',views.sifre,name = "sifre"),
    url(r'^profilegitmen/',views.profilegitmen,name = "profilegitmen"),
    url(r'^pt_al/',views.pt_al,name = "pt_al"),
    #path('uretim/',views.uretim,name = "uretim"),
]

templates/giris.html
<!doctype html>
{% extends 'govde.html' %}
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block baslik%}
        Atlas GYM - PT -- [> GİRİŞ YAP <]
    {% endblock baslik %}</title>

</head>

<body>
{% block govde_slider %}

<div  class="row">
    <div class="col-md-12">



      <form method="POST" action="{% url 'kullanicilar:giris' %}">{% csrf_token %}

  <div class="form-group row">
    <div class="col-sm-5 mx-auto">
        <h3>Giriş Yap</h3>
      <hr color="#007BFF">
      <input name="kullanici_adi" type="text" class="form-control" id="inputkullanici" placeholder="Kullanıcı adı">
    </div>
  </div>

  <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input name="sifre" type="password" class="form-control" id="inputPassword" placeholder="Şifre">
    </div>
  </div>



  <div class="form-group row">
    <div class="col-sm-5 mx-auto">
      <button type="submit" class="btn btn-primary form-control">Giriş Yap</button>
        <hr color="#007BFF">
    </div>
  </div>


      <div class="form-group row">
    <div class="col-sm-5 mx-auto">
      {% if messages %}

        {% for message in messages %}
            {% if message.tags == "info" %}
                <div class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
        {% endfor %}
        {% endif %}
    </div>
  </div>
</form>











</div>
</div>
{% endblock govde_slider %}

</body>
</html>

templates/kayit.html
<!doctype html>
{% extends 'govde.html' %}
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block baslik%}
        Atlas GYM - PT -- [> KAYIT OL <]
    {% endblock baslik %}</title>

</head>
<body>
{% block govde_slider %}



<div class="row"> <!-- burası tablı kayıt ol menü başlangıcı ----------------------------------- -->
    <div class="col-md-12">
        <div class="form-group row">
    <div class="col-sm-5 mx-auto">

      <h3>Kayıt Ol</h3>
    <hr color="#007BFF">
    </div>
  </div>

<div class="form-group row">
    <div class="col-sm-5 mx-auto">
<ul class="nav nav-tabs" id="myTab" role="tablist">
    {% if sayfa == "uye" %}
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Üye</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Eğitmen</a>
      </li>
    {% endif %}
    {% if sayfa == "egitmen" %}
        <li class="nav-item">
        <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="false">Üye</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Eğitmen</a>
      </li>
    {% endif %}
    {% if sayfa == None %}
    <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Üye</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Eğitmen</a>
      </li>
    {% endif %}

</ul>
    </div> </div>

<div class="tab-content" id="myTabContent">
    {% if sayfa == None %}
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    {% endif %}


   {% if sayfa == "uye" %}
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
   {% endif %}
   {% if sayfa == "egitmen" %}
      <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
   {% endif %}
      <form method="POST" action="{% url 'kullanicilar:kayit' %}">{% csrf_token %}

  <div class="form-group row">
    <div class="col-sm-5 mx-auto">

      <input value="{{ kullanici_adi }}" name="kullanici_adi" type="text" class="form-control" id="inputkullanici" placeholder="Kullanıcı adı">
    </div>
  </div>

  <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input name="sifre" type="password" class="form-control" id="inputPassword" placeholder="Şifre">
    </div>
  </div>

  <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input name="confirm" type="password" class="form-control" id="inputPassword2" placeholder="Şifrenizi yeniden yazın">
    </div>
  </div>

   <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input value="{{ email }}" name="email" type="email" class="form-control" id="inputEmail" placeholder="Email">
    </div>
  </div>


  <div class="form-group row">
    <div class="col-sm-5 mx-auto">
      <button type="submit" class="btn btn-primary form-control">Kayıt Ol</button>
        <hr color="#007BFF">
    </div>
  </div>
          <input name="kim" type="text" hidden="True" value="uye">
</form>



  </div>



{% if sayfa == "egitmen" %}
  <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
{% else %}
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
{% endif %}
      <form method="POST" action="{% url 'kullanicilar:kayit' %}">{% csrf_token %}

  <div class="form-group row">
    <div class="col-sm-5 mx-auto">
      <input name="hoca_kullanici_adi" type="text" class="form-control" id="inputkullanici" placeholder="Kullanıcı adı">
    </div>
  </div>

  <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input name="hoca_sifre" type="password" class="form-control" id="inputPassword" placeholder="Şifre">
    </div>
  </div>

  <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input name="hoca_confirm" type="password" class="form-control" id="inputPassword2" placeholder="Şifrenizi yeniden yazın">
    </div>
  </div>

   <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input name="hoca_email" type="email" class="form-control" id="inputEmail" placeholder="Email">
    </div>
  </div>
    <div class="form-group row">

    <div class="col-sm-5 mx-auto">
      <input  name="hoca_egitmen_kodu" type="number" class="form-control" id="inputPassword2" placeholder="Eğitmen kodunuzu yazın" data-toggle="tooltip" data-placement="right" title="Kayıt olmak için İlkay KURU'dan aldığınız 4 haneli kod">
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-5 mx-auto">
      <button type="submit" class="btn btn-primary form-control">Kayıt Ol</button>
        <hr color="#007BFF">
    </div>
  </div>
          <input name="kim" type="text" hidden="True" value="egitmen">
</form>

  </div>

</div>



<div class="form-group row">
    <div class="col-sm-5 mx-auto">
    {% if messages %}

    {% for message in messages %}
    {% if message.tags == "info" %}
        <div class="alert alert-danger">{{ message }}</div>
    {% else %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endif %}


    {% endfor %}

    {% endif %}
    </div></div>
</div>
</div>

{% endblock govde_slider %}
</body>
</html>

templates/profil_goruntule.html
<!doctype html>
{% extends 'govde.html' %}
{% load static %}
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">


  <title>{% block baslik%}
    Atlas GYM - PT -- [> PROFİL <]
  {% endblock baslik %}</title>

</head>

<body>

  {% block govde_slider %}



  <div class="container bootstrap snippet">
    <div  class="row">
      <div class="col-sm-12">
        {% if isim == "" %}
        <h3>{{ request.session.member.upper }}</h3>
        {% else %}
        <h3>{{ isim.upper }}</h3>

        {% endif %}

      </div>

    </div>
    <br>

    <hr color="#007BFF">
<form class="form" action="{% url 'kullanicilar:profil_goruntule' %}" method="post" id="registrationForm" enctype = "multipart/form-data">{% csrf_token %}
    <div class ="form-row"> <!--/form row**********************************************-->
      <div  class="form-group col-md-3">
        <div class="card" >
          <label for="fileUpload">
            <img class="card-img-top" name="resimYok" height="190" width="190" id="fileResim" src="{{ resim }}" class="avatar img-circle img-thumbnail" alt="avatar">
            <input src="{{ resim }}" name="resimDosya" accept="image/png, image/jpeg, image/jpg" onchange="$('#fileResim')[0].src = window.URL.createObjectURL(this.files[0])" id="fileUpload" type="file" hidden="True" class="text-center center-block file-upload">

            <h6 align="center">Fotoğraf Ekleyin</h6></label>
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-left"><span class="pull-left"><strong>Paylaşımlar </strong></span><span style="float:right;" class="badge badge-dark"> 128</span></li>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Programlar </strong></span><span style="float:right;" class="badge badge-dark"> 3</span></li>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Diyetler </strong></span><span style="float:right;" class="badge badge-dark"> 2</span></li>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Aldığı PT'ler </strong></span><span style="float:right;" class="badge badge-dark"> 2</span></li>
              {% if trainer == "" or pt_kontrol == 0 %}
              <li class="list-group-item text-left"><span class="pull-left"><strong>Aktif PT </strong></span><span style="float:right;" class="badge badge-danger"> Yok</span></li>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Eğitmen </strong></span><span style="float:right;" class="badge badge-danger"> Atanmadı</span></li>
              {% else %}
              <li class="list-group-item text-left"><span class="pull-left"><strong>Aktif PT </strong></span><span style="float:right;" class="badge badge-success">{% if pt_kontrol == 1 %}VAR</span>{% endif %}</li>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Eğitmen </strong></span><a style="float:right;" href="#" class="badge badge-success">{{ trainer.upper }}</a></li>
              {% endif %}
            </ul>
          </div>
        </div>

        <div style="margin-top:10px;" class="form-group col-md-9">
          <div class="form-row">

            <div  class="form-group col-md-12">

              <label class="col-form-label" for="first_name"><h5>İsim</h5></label>
              <input type="text" value="{{isim.upper}}" class="form-control" name="isim" id="first_name" placeholder="İsminiz">

            </div>

            <div class="form-group col-md-6 mr-auto">

              <label class="col-form-label" for="date"><h5>Doğum Tarihi</h5></label>
              <input id="date" value="{{dogum_tarihi}}" type="date" name="dogum_tarihi"  class="form-control">

            </div>

            <div class="form-group col-md-6 mr-auto">

             <label class="col-form-label" for="telefon"><h5>Cep Telefonu</h5></label>
             <input class="form-control" value="{{telefon}}"type="tel" data-country="TR" value="(555)-555-5555" maxlength="10" name="telefon" id="telefon" placeholder="Telefon Numaranızı Girin">

           </div>


           <div class="form-group col-md-6 mr-auto">

            <label class="col-form-label" for="email"><h5>Email</h5></label>
            <input type="email" value="{{email}}" class="form-control" name="email" id="email" placeholder="siz@email.com">

          </div>

          <div class="form-group col-md-6 mr auto">
            <label class="col-form-label" for="cinsiyet"><h5>Cinsiyet</h5></label>
            <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="cinsiyet" name="cinsiyet">
             <option>SEÇİNİZ</option>

             {% if cinsiyet == "E" %}

             <option value="K">KIZ</option>
             <option selected value="E">ERKEK</option>
             {% elif cinsiyet == "K" %}


             <option selected value="K">KIZ</option>
             <option value="E">ERKEK</option>
             {% else %}

             <option value="K">KIZ</option>
             <option value="E">ERKEK</option>

             {% endif %}
           </select>
         </div>




         <div class="form-group col-md-6 mr auto">

          <label class="col-form-label" for="kilo"><h5>Kilo</h5></label>
          <input type="number" value="{{kilo}}" class="form-control" id="kilo" name="kilo" max="500" min="0" placeholder="Kilonuz">

        </div>

        <div class="form-group col-md-6 mr-auto">

          <label class="col-form-label" for="boy"><h5>Boyunuz (cm)</h5></label>
          <input type="number" value="{{boy}}" class="form-control" id="boy" name="boy" max="500" min="0" placeholder="Boyunuz">

        </div>



        <div class="form-group col-md-12">

          <label class="col-form-label" for="problem"><h5>Sağlık Probleminiz Var mı?</h5></label>
          <textarea class="form-control" id="problem" name="problem" placeholder="Herhangi bir sağlık probleminiz varsa belirtiniz.">{{problem.upper}}</textarea>

        </div>
              <div class="form-group col-md-12">


          <button class="btn btn-success btn-block" type="submit">KAYDET</button>
              </div>







          </div>




    </div>

  </div>


</form>







</div>





  {% endblock %}

</body>
</html>





templates/profil_goruntule_egitmen.html
<!doctype html>
{% extends 'govde.html' %}
{% load static %}
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">


  <title>{% block baslik%}
    Atlas GYM - PT -- [> EĞİTMEN PROFİLİ <]
  {% endblock baslik %}</title>

</head>

<body>

  {% block govde_slider %}
  <div class="container bootstrap snippet">
    <div  class="row">
      <div class="col-sm-12">
        {% if isim == "" %}
        <h3>{{ request.session.member.upper }}</h3>
        {% else %}
        <h3>{{ isim.upper }}</h3>

        {% endif %}
      </div>
    </div>
    <br>

    <hr color="#007BFF">
<form class="form" action="{% url 'kullanicilar:profilegitmen' %}" method="post" id="registrationForm" enctype = "multipart/form-data">{% csrf_token %}
    <div class ="form-row"> <!--/form row**********************************************-->
      <div  style="margin-top:7px;" class="form-group col-md-3">
        <div class="card" >
          <label for="fileUpload">
            <img class="card-img-top" name="resimYok" height="192" width="192" id="fileResim" src="{{ resim }}" class="avatar img-circle img-thumbnail" alt="avatar">
            <input src="{{ resim }}" name="resimDosya" accept="image/png, image/jpeg, image/jpg" onchange="$('#fileResim')[0].src = window.URL.createObjectURL(this.files[0])" id="fileUpload" type="file" hidden="True" class="text-center center-block file-upload">
            <h5 align="center">Fotoğraf Ekleyin</h5></label>
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-left"><span class="pull-left"><strong>Paylaşımlar </strong></span><span style="float:right;" class="badge badge-dark"> 128</span></li>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Verdiği PT'ler </strong></span><span style="float:right;" class="badge badge-dark"> 2</span></li>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Aktif PT'ler </strong></span><span style="float:right;" class="badge badge-success">{% if pt_kontrol == 1 %}VAR</span>{% endif %}</li>
            </ul>
          </div>
        </div>

        <div class="form-group col-md-9">
          <div class="form-row">

            <div class="form-group col-md-12">

              <label class="col-form-label" for="first_name"><h5>İsim</h5></label>
              <input type="text" value="{{isim.upper}}" class="form-control" name="isim" id="first_name" placeholder="İsminiz">

            </div>




            <div class="form-group col-md-6 mr-auto">

              <label class="col-form-label" for="date"><h5>Doğum Tarihi</h5></label>
              <input id="date" value="{{dogum_tarihi}}" type="date" name="dogum_tarihi"  class="form-control">

            </div>

            <div class="form-group col-md-6 mr-auto">

             <label class="col-form-label" for="telefon"><h5>Cep Telefonu</h5></label>
             <input class="form-control" value="{{telefon}}"type="tel" data-country="TR" value="(555)-555-5555" maxlength="10" name="telefon" id="telefon" placeholder="Telefon Numaranızı Girin">

           </div>


           <div class="form-group col-md-6 mr-auto">

            <label class="col-form-label" for="email"><h5>Email</h5></label>
            <input type="email" value="{{email}}" class="form-control" name="email" id="email" placeholder="siz@email.com">

          </div>

          <div class="form-group col-md-6 mr auto">
            <label class="col-form-label" for="cinsiyet"><h5>Cinsiyet</h5></label>
            <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="cinsiyet" name="cinsiyet">
             <option>SEÇİNİZ</option>
             {% if cinsiyet == "E" %}
             <option value="K">KIZ</option>
             <option selected value="E">ERKEK</option>
             {% elif cinsiyet == "K" %}
             <option selected value="K">KIZ</option>
             <option value="E">ERKEK</option>
             {% else %}
             <option value="K">KIZ</option>
             <option value="E">ERKEK</option>
             {% endif %}
           </select>
         </div>

         <div class="form-group col-md-6 mr auto">
            <label class="col-form-label" for="universite"><h5>Üniversite</h5></label>
            <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="universite" name="uni">
                <option>SEÇİNİZ</option>
                {% if uni %}
                    {% for u in uni %}
                        <option  value="{{u}}">{{ u }}</option>
                    {% endfor %}
                {% endif %}

                {% if uni_secilen %}
                    <option selected value="{{uni_secilen}}">{{ uni_secilen }}</option>
                {% endif %}


           </select>
         </div>

          <div class="form-group col-md-6 mr auto">
            <label class="col-form-label" for="neresi"><h5>Bölüm</h5></label>
            <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="neresi" name="bolum">
                <option>SEÇİNİZ</option>
                {% if bolum %}
                    {% for b in bolum %}
                        <option value="{{b}}">{{ b }}</option>
                    {% endfor %}
                {% endif %}

                {% if bolum_hangisi %}
                    <option selected value="{{bolum_hangisi}}">{{ bolum_hangisi }}</option>
                {% endif %}


           </select>
         </div>

              <div class="form-group col-md-12">

            <br>
          <button  class="btn btn-lg btn-success btn-block" type="submit">KAYDET</button>
              </div>
          </div>

    </div>

  </div>


</form>







</div>





  {% endblock %}

</body>
</html>





templates/pt_al.html
<!doctype html>
{% extends 'govde.html' %}
{% load static %}
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block baslik%}
    Atlas GYM - PT -- [> PT AL <]
  {% endblock baslik %}</title>
</head>
<body>

{% block govde_hocalar %}

{% endblock govde_hocalar %}





{% block govde_slider %}

<!------------------------------BAŞLIK-------------------------------------->

<div class="row row-fluid">
    <div class="col-md-9 mx-auto">
<div  class="jumbotron p-4 p-md-0 text-white rounded bg-dark">
    <img  class="img-fluid  d-block mx-auto" src="{% static 'files/pt2.jpg' %}" >
        <div  class="col-md-7 px-3">
          <h1 class="display-5 font-italic">Özel ders ile hedeflerinize daha kolay ulaşın</h1>
          <p class="lead my-3">Profesyönel eğitmenlerimizden, amaçlarınıza uygun olanını seçin.</p>
        </div>
      </div>
</div>
</div>
<!-------------------------------HOCALAR--------------------------------------------------->
<h3 class="h2 font-weight-normal text-primary text-center mb-0">EĞİTMENLERİMİZ</h3>

<hr color="#007BFF">
<br>
<form class="form" action="{% url 'kullanicilar:pt_al' %}" method="post" id="registrationForm" enctype = "multipart/form-data">{% csrf_token %}

<div class="table-responsive">
<table class="table table-sm table-hover">
  <thead>
    <tr align="center">
      <th scope="col">#</th>
      <th scope="col">İsim</th>
      <th scope="col">Okul</th>
      <th scope="col">Bölüm</th>
      <th scope="col">Uzmanlık Alanı</th>
      <th scope="col">Öğrenci Sayısı</th>
      <th scope="col">CV</th>
    </tr>
  </thead>
  <tbody>

        {% for e in egitmen %}

            <tr align="center">
              <th scope="row">{{ e.id }}</th>
              <td>{{ e.isim.upper }} {{ e.soyisim.upper }}</td>
              <td>{{ e.universite.upper }}</td>
              <td>{{ e.bolum.upper }}</td>
                <td>FİTNESS</td>
                <td>9</td>
                <td>ANTRENÖRLÜK</td>
            </tr>

        {% endfor %}

  </tbody>
</table>
</div>
</form>
<hr color="#007BFF">

<!-------------------------------SATIN ALMA-------------------------------------------------->

<div class="container mb-5 mt-5">
    <div class="pricing card-deck flex-column flex-md-row mb-3">
        <div class="card card-pricing text-center px-3 mb-4">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">Starter Paket</span>
            <div class="bg-transparent card-header pt-4 border-0">
                <h3 class="h2 font-weight-normal text-primary text-center mb-0" data-pricing-value="60"><span class="h6 text-muted ml-1">Antrenman başına / </span>60<span class="price"> TL</span></h3>
            </div>
            <div class="card-body pt-0">
                <ul class="list-unstyled mb-4">
                    <li>Size özel antrenman desteği</li>
                    <li>Temel beslenme desteği</li>
                </ul>

            </div>
            <button type="button" class="btn btn-outline-secondary mb-3">Satın al</button>
        </div>
        <div class="card card-pricing popular shadow text-center px-3 mb-4">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">Professional Paket</span>
            <div class="bg-transparent card-header pt-4 border-0">
                <h3 class="h2 font-weight-normal text-primary text-center mb-0" data-pricing-value="85"><span class="h6 text-muted ml-1">Antrenman başına / </span>85<span class="price"> TL</span></h3>
            </div>
            <div class="card-body pt-0">
                <ul class="list-unstyled mb-4">
                    <li>Size özel antrenman desteği</li>
                    <li>Temel beslenme desteği</li>
                </ul>

            </div>
            <button type="button" class="btn btn-outline-secondary mb-3">Satın al</button>
        </div>
        <div class="card card-pricing text-center px-3 mb-4">
            <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">Full Paket</span>
            <div class="bg-transparent card-header pt-4 border-0">
                <h3 class="h2 font-weight-normal text-primary text-center mb-0" data-pricing-value="100"><span class="h6 text-muted ml-1">Antrenman başına / </span>100<span class="price"> TL</span></h3>
            </div>
            <div class="card-body pt-0">
                <ul class="list-unstyled mb-4">
                    <li>Size özel antrenman desteği</li>
                    <li>Temel beslenme desteği</li>
                </ul>

            </div>
            <button type="button" class="btn btn-outline-secondary mb-3">Satın al</button>
        </div>

    </div>
</div>



<!----------------------------------------------------------------------------->







{% endblock %}

</body>
</html>